### PR TITLE
chore: update deps to latest [patch]

### PR DESCRIPTION
**Pull request by TomPridham**
## Change Type

* [ ] Feature
* [x] Chore
* [ ] Bug Fix

## Change Level

* [ ] major
* [ ] minor
* [x] patch

## Further Information (screenshots, bug report links, etc)
updates deps to latest so we can use the newer TS plugins without issue

### CODE REVIEW

**Comment by cfbender** [comment]
Hot diggity. What issue were you having before?

**Comment by TomPridham** [comment]
i was getting errors that react was being used before it was defined, all the stuff in their repo said to make sure all the plugins were at the same level

**Comment by TomPridham** [comment]
i'm in the process of updating all the deps in www to try and fix some image issues we've been having

**Review by cfbender — APPROVED** [review]
I was having the same issues when messing around updating deps on ampere, this seemed to do the trick :+1:

**Pull request merged**
