### PR TITLE
fix: enable ts no-use-before-define[patch]

### PR DESCRIPTION
**Pull request by TomPridham**
we had the normal eslint rule turned off, but didn't have the TS version turned on

### CODE REVIEW

**Comment by jeff-foster** [comment]
how much will current repos be affected by turning on this rule?
I'd guess we're almost always defining beforehand and hoping this won't require much refactoring anywhere

**Comment by brettinternet** [comment]
It won't affect current repos until you update the dep

**Comment by jeff-foster** [comment]
@brettinternet yes, thanks. sorry poorly-formed question. I mean turning it on by updating deps. I'm considering a likely scenario of an unknowing dev needing/or choosing to update deps in the future. With a shared config I think it's useful to always ask what's affected, and may be a good decision to update and tackle the hopefully small tech debt immediately

@TomPridham perhaps too trivial, but would it be useful to document the rule change in the tags/changelog/release/whatev?

I'm also curious if we've been already following the rule by habit, and what caused the discovery that the rule was off

**Review by jeff-foster — APPROVED** [review]
LGTM, don't let my comments hold up the merge

**Comment by TomPridham** [comment]
It's mostly been me scrolling to try and find something and being confused until I find it declared above where it is first used. I don't anticipate it will cause many issues because it should only really affect functions. Typescript complains if you use a non-function variable before it's defined.
We could change the tag to a minor. That's probably more correct anyways

**Pull request merged**
