### PR TITLE
#minor bump eslint to 8.x and related fixes

### PR DESCRIPTION
**Pull request by cfbender**
WOOOO FINALLY

https://github.com/xjamundx/eslint-plugin-promise/pull/219 is closed so we can do the damn thing

### CODE REVIEW

**Comment by TomPridham** [comment]
are node 12/14 not supported on the new one? we could remove thm from the test matrix if so

**Comment by cfbender** [comment]
@TomPridham they should beL https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#drop-old-node, they only dropped the odd versions

**Comment by cfbender** [comment]
but I wonder if one of the other dependencies isn't

**Comment by TomPridham** [comment]
i'd be fine removing them, tbh. i don't think we have anything using those versions

**Comment by cfbender** [comment]
same, we shouldn't be using node versions that old even if they are LTS IMO lol

**Review by TomPridham — APPROVED** [review]

**Pull request merged**
